title: "Merhaba!"
description: "This site is for my projects and future ideas."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - projects.md
  - resume.md
